name: learn_flutter_step_by_step
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  #https://pub.dev/packages/get
  get: ^4.6.5
  #https://pub.dev/packages/intl
  intl: ^0.18.0
  #https://pub.dev/packages/logger
  logger: ^1.3.0
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.18
  #https://pub.dev/packages/shimmer
  shimmer: ^2.0.0
  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^3.0.3
  #https://pub.dev/packages/avatar_glow
  avatar_glow: ^2.0.2
  #https://pub.dev/packages/in_app_review
  in_app_review: ^2.0.6
  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
