name: ketquaxoso
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2024.04.13+20240413

environment:
  sdk: '>=2.19.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  applovin_max: ^3.9.2
  animated_introduction: ^1.0.4
  animated_notch_bottom_bar: ^1.0.2
  calendar_timeline_sbk: ^1.1.7
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  package_info_plus:
  avatar_glow: ^3.0.1
  in_app_review: ^2.0.9
  url_launcher: ^6.2.6
  animated_text_kit: ^4.2.2
  blur: ^3.1.0
  cached_network_image: ^3.3.1
  connection_notifier: ^2.0.1
  dio: ^5.4.2+1
  flutter_pretty_dio_logger: ^3.0.0
  easy_debounce: ^2.0.3
#  flutter_local_notifications: ^17.0.1
  flutter_displaymode: ^0.6.0
  flutter_native_splash:
  flutter_widget_from_html: ^0.14.11
  webview_flutter: ^4.7.0
  restart_app: ^1.2.1
  panara_dialogs: ^0.1.4
  platform_device_id: ^1.0.1
  lottie: ^3.1.0
  share_plus: ^8.0.3
  marquee: ^2.2.3
  kenburns_nullsafety: ^1.0.1
  permission_handler:
  toggle_switch: ^2.3.0
  highlight_text: ^1.7.0
  relative_dialog: ^0.2.1
  flutter_udid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

  #https://pub.dev/packages/flutter_app_name
  #flutter_app_name: ^0.1.1
  #name: "Flutter tutorials"

#  change_app_package_name: ^1.1.0

  #https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  #  fonts:
  #    - family: Pacifico
  #      fonts:
  #        - asset: data_repo/fonts/Pacifico-Regular.ttf
  #          weight: 400
  assets:
    - assets/files/
    - assets/videos/
    - assets/images/
